# Generated by Django 6.0.1 on 2026-01-31 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Lịch sử hoạt động', 'verbose_name_plural': 'Lịch sử hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Khu vực', 'verbose_name_plural': 'Khu vực'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Bãi đỗ xe', 'verbose_name_plural': 'Bãi đỗ xe'},
        ),
        migrations.AlterModelOptions(
            name='parkingtype',
            options={'verbose_name': 'Loại bãi đỗ xe', 'verbose_name_plural': 'Loại bãi đỗ xe'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Giá vé', 'verbose_name_plural': 'Giá vé'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Doanh thu', 'verbose_name_plural': 'Doanh thu'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=200, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='Bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.area', verbose_name='Khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='available_slots',
            field=models.IntegerField(verbose_name='Số chỗ trống'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.IntegerField(verbose_name='Tổng số chỗ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingtype', verbose_name='Loại bãi'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='status',
            field=models.CharField(choices=[('open', 'Đang hoạt động'), ('closed', 'Tạm ngưng')], default='open', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='parkingtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Loại bãi đỗ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='parking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingtype', verbose_name='Loại bãi'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_per_hour',
            field=models.FloatField(verbose_name='Giá theo giờ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time_range',
            field=models.CharField(max_length=50, verbose_name='Khung giờ'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='month',
            field=models.IntegerField(verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='Bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='total_amount',
            field=models.FloatField(verbose_name='Tổng doanh thu'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='year',
            field=models.IntegerField(verbose_name='Năm'),
        ),
    ]
