# Generated by Django 6.0.2 on 2026-02-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-time'], 'verbose_name': 'Nhật ký hoạt động', 'verbose_name_plural': 'Nhật ký hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Khu vực', 'verbose_name_plural': 'Danh sách khu vực'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Bãi đỗ xe', 'verbose_name_plural': 'Danh sách bãi đỗ xe'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='parking',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('system', 'Hệ thống'), ('user', 'Người dùng')], default='system', max_length=20, verbose_name='Loại hoạt động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.area', verbose_name='Khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='available_slots',
            field=models.IntegerField(verbose_name='Chỗ trống'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.IntegerField(verbose_name='Sức chứa'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên bãi xe'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.IntegerField(verbose_name='Giá/giờ'),
        ),
    ]
