# Generated by Django 6.0.2 on 2026-02-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_activitylog_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp')], max_length=20, verbose_name='Loại xe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='Bãi đỗ xe')),
            ],
            options={
                'verbose_name': 'Người sử dụng đỗ xe',
                'verbose_name_plural': 'Danh sách người sử dụng đỗ xe',
            },
        ),
    ]
