# Generated by Django 6.0.2 on 2026-03-06 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_activitylog_options_alter_area_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='parking_type',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='parking_lot',
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhat ky hoat dong', 'verbose_name_plural': 'Nhat ky hoat dong'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Khu vuc', 'verbose_name_plural': 'Danh sach khu vuc'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Bai do xe', 'verbose_name_plural': 'Danh sach bai do xe'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='parking_lot',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='status',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('system', 'He thong'), ('vehicle', 'Xe')], default='system', max_length=20, verbose_name='Loai hoat dong'),
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mo ta'),
        ),
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vi do'),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh do'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Dang hoat dong'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='Gia mac dinh (khong dung)'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='revenue',
            field=models.PositiveIntegerField(default=0, verbose_name='Doanh thu'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Hanh dong'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi thuc hien'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten khu vuc'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dia chi'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.area', verbose_name='Khu vuc'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Suc chua'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten bai xe'),
        ),
        migrations.CreateModel(
            name='ParkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'O to'), ('motorbike', 'Xe may'), ('bike', 'Xe dap')], max_length=20, verbose_name='Loai xe')),
                ('price_per_hour', models.PositiveIntegerField(verbose_name='Gia / gio (VND)')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parking.parkinglot', verbose_name='Bai do xe')),
            ],
            options={
                'verbose_name': 'Gia gui xe',
                'verbose_name_plural': 'Bang gia gui xe',
                'unique_together': {('parking_lot', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='ParkingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ho va ten')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='So dien thoai')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dia chi')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Bien so xe')),
                ('vehicle_type', models.CharField(choices=[('car', 'O to'), ('motorbike', 'Xe may'), ('bike', 'Xe dap')], max_length=20, verbose_name='Loai xe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian vao bai')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='Bai do xe')),
            ],
            options={
                'verbose_name': 'Nguoi su dung do xe',
                'verbose_name_plural': 'Danh sach nguoi su dung do xe',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ParkingType',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
