# Generated by Django 6.0.2 on 2026-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang đỗ'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('system', 'Hệ thống'), ('vehicle', 'Xe')], default='system', max_length=20, verbose_name='Loại hoạt động'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vào bãi'),
        ),
    ]
