# Generated by Django 6.0.2 on 2026-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkinguser_is_active_alter_activitylog_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='available_slots',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('system', 'Hệ thống'), ('vehicle', 'Xe')], max_length=20, verbose_name='Loại hoạt động'),
        ),
    ]
