# Generated by Django 6.0.2 on 2026-04-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinguser_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='area_sq_m',
            field=models.FloatField(default=0, verbose_name='Dien tich (m2)'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='polygon_geojson',
            field=models.TextField(blank=True, default='', verbose_name='Ranh gioi (GeoJSON)'),
        ),
    ]
