# Generated by Django 6.0.2 on 2026-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_parkinglot_available_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.FloatField(default=10.7769, verbose_name='Vĩ độ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.FloatField(default=106.7009, verbose_name='Kinh độ'),
            preserve_default=False,
        ),
    ]
