# Generated by Django 6.0.2 on 2026-04-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkinglot_area_sq_m_parkinglot_polygon_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='long_description',
            field=models.TextField(blank=True, default='', verbose_name='Mo ta chi tiet'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mo ta ngan'),
        ),
    ]
