# Generated by Django 6.0.2 on 2026-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_area_latitude_area_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhật ký hoạt động', 'verbose_name_plural': 'Nhật ký hoạt động'},
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
    ]
