# Generated by Django 6.0.2 on 2026-04-17 02:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkinglot_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='parking_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Hinh anh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian tao')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parking.parkinglot', verbose_name='Bai do xe')),
            ],
            options={
                'verbose_name': 'Hinh anh bai do xe',
                'verbose_name_plural': 'Hinh anh bai do xe',
                'ordering': ['id'],
            },
        ),
    ]
