# Generated by Django 6.0.1 on 2026-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
    ]
