# Generated by Django 6.0.2 on 2026-02-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bicycle', 'Xe đạp')], max_length=20, verbose_name='Loại xe')),
                ('price_per_hour', models.PositiveIntegerField(verbose_name='Giá / giờ (VNĐ)')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parking.parkinglot', verbose_name='Bãi đỗ xe')),
            ],
            options={
                'verbose_name': 'Giá gửi xe',
                'verbose_name_plural': 'Bảng giá gửi xe',
                'unique_together': {('parking_lot', 'vehicle_type')},
            },
        ),
    ]
