# Generated by Django 6.0.1 on 2026-02-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_parkinglot_latitude_parkinglot_longitude'),
        ('parking', '0008_parkingprice'),
    ]

    operations = [
    ]
