# Generated by Django 6.0.2 on 2026-04-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0008_parkinglotimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingRegistrationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=100, verbose_name="Ho va ten")),
                ("phone", models.CharField(max_length=15, verbose_name="So dien thoai")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Dia chi")),
                ("license_plate", models.CharField(max_length=20, verbose_name="Bien so xe")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "O to"), ("motorbike", "Xe may"), ("bike", "Xe dap")],
                        max_length=20,
                        verbose_name="Loai xe",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Ghi chu")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Cho duyet"), ("approved", "Da duyet"), ("rejected", "Khong duyet")],
                        default="pending",
                        max_length=20,
                        verbose_name="Trang thai",
                    ),
                ),
                ("reviewed_note", models.CharField(blank=True, default="", max_length=255, verbose_name="Ghi chu duyet")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Thoi gian xu ly")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Thoi gian gui")),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_requests",
                        to="parking.parkinglot",
                        verbose_name="Bai do xe mong muon",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_parking_registration_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nguoi xu ly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Don dang ky gui xe",
                "verbose_name_plural": "Don dang ky gui xe",
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
