# Generated by Django 6.0.2 on 2026-02-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_parkingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Sức chứa'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá mặc định (không dùng)'),
        ),
        migrations.AlterField(
            model_name='parkingprice',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp')], max_length=20, verbose_name='Loại xe'),
        ),
    ]
