# Generated by Django 6.0.2 on 2026-02-05 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_merge_20260205_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='#999999', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parkinguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='area',
            name='description',
        ),
        migrations.RemoveField(
            model_name='area',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='area',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='parkinguser',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='has_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='has_ev_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings', to='parking.area'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_users', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingstatus'),
        ),
        migrations.DeleteModel(
            name='ParkingPrice',
        ),
    ]
