# Generated by Django 6.0.2 on 2026-04-17 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0009_parkingregistrationrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingregistrationrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parking_registration_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tai khoan gui don",
            ),
        ),
    ]
