# Generated by Django 6.0.2 on 2026-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_parkinglot_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='district',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
