# Generated by Django 6.0.2 on 2026-04-17 04:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parkingregistrationrequest_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhật ký hoạt động', 'verbose_name_plural': 'Nhật ký hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Khu vực', 'verbose_name_plural': 'Danh sách khu vực'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Bãi đỗ xe', 'verbose_name_plural': 'Danh sách bãi đỗ xe'},
        ),
        migrations.AlterModelOptions(
            name='parkinglotimage',
            options={'ordering': ['id'], 'verbose_name': 'Hình ảnh bãi đỗ xe', 'verbose_name_plural': 'Hình ảnh bãi đỗ xe'},
        ),
        migrations.AlterModelOptions(
            name='parkingprice',
            options={'verbose_name': 'Giá gửi xe', 'verbose_name_plural': 'Bảng giá gửi xe'},
        ),
        migrations.AlterModelOptions(
            name='parkingregistrationrequest',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Đơn đăng ký gửi xe', 'verbose_name_plural': 'Đơn đăng ký gửi xe'},
        ),
        migrations.AlterModelOptions(
            name='parkinguser',
            options={'verbose_name': 'Người sử dụng đỗ xe', 'verbose_name_plural': 'Danh sách người sử dụng đỗ xe'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('system', 'Hệ thống'), ('vehicle', 'Xe')], default='system', max_length=20, verbose_name='Loại hoạt động'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.area', verbose_name='Khu vực'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Sức chứa'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='long_description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên bãi xe'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='polygon_geojson',
            field=models.TextField(blank=True, default='', verbose_name='Ranh giới (GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá mặc định (không dùng)'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='parkinglotimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='parkinglotimage',
            name='image',
            field=models.FileField(upload_to='parking_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='parkinglotimage',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parking.parkinglot', verbose_name='Bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='parkingprice',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parking.parkinglot', verbose_name='Bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='parkingprice',
            name='price_per_hour',
            field=models.PositiveIntegerField(verbose_name='Giá / giờ (VND)'),
        ),
        migrations.AlterField(
            model_name='parkingprice',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp')], max_length=20, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_registration_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản gửi đơn'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='parking.parkinglot', verbose_name='Bãi đỗ xe mong muốn'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parking_registration_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='reviewed_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú duyệt'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Không duyệt')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='parkingregistrationrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp')], max_length=20, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vào bãi'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi xác thực'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email đã xác thực'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang đỗ'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Biển số xe'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='Bãi đỗ xe'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='parkinguser',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp')], max_length=20, verbose_name='Loại xe'),
        ),
    ]
