# Generated by Django 6.0.2 on 2026-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0011_alter_activitylog_options_alter_area_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("code", models.CharField(max_length=6, verbose_name="Mã OTP")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Hết hạn lúc")),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mã OTP",
                "verbose_name_plural": "Danh sách mã OTP",
                "indexes": [
                    models.Index(
                        fields=["email", "is_used"], name="parking_otp_email_6fe5e9_idx"
                    )
                ],
            },
        ),
    ]
