# Generated by Django 6.0.2 on 2026-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('mission_title', models.CharField(max_length=255)),
                ('mission_description', models.TextField()),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='intro/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
