--
-- PostgreSQL database dump
--

\restrict KHL9nQvZDMz5d5Am3tC83OKT76oxglC2BM9MG00kVA2PM5dRWvKEksME5Jtj5sU

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: parking_activitylog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_activitylog (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer,
    type character varying(20) NOT NULL
);


ALTER TABLE public.parking_activitylog OWNER TO postgres;

--
-- Name: parking_activitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_activitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_area; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_area (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    latitude double precision,
    longitude double precision,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.parking_area OWNER TO postgres;

--
-- Name: parking_area_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_area ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_introductionpage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_introductionpage (
    id bigint NOT NULL,
    hero_title character varying(255) NOT NULL,
    hero_description text NOT NULL,
    mission_title character varying(255) NOT NULL,
    mission_description text NOT NULL,
    about_title character varying(255) NOT NULL,
    about_description text NOT NULL,
    hero_image character varying(100),
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.parking_introductionpage OWNER TO postgres;

--
-- Name: parking_introductionpage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_introductionpage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_introductionpage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_otpcode; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_otpcode (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL
);


ALTER TABLE public.parking_otpcode OWNER TO postgres;

--
-- Name: parking_otpcode_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_otpcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_otpcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_parkinglot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_parkinglot (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(255) NOT NULL,
    latitude double precision,
    longitude double precision,
    capacity integer NOT NULL,
    area_id bigint,
    district character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    price_per_hour integer NOT NULL,
    revenue integer NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    area_sq_m double precision NOT NULL,
    polygon_geojson text NOT NULL,
    long_description text NOT NULL,
    short_description character varying(255) NOT NULL,
    CONSTRAINT parking_parkinglot_capacity_978bc67d_check CHECK ((capacity >= 0)),
    CONSTRAINT parking_parkinglot_price_per_hour_check CHECK ((price_per_hour >= 0)),
    CONSTRAINT parking_parkinglot_revenue_check CHECK ((revenue >= 0))
);


ALTER TABLE public.parking_parkinglot OWNER TO postgres;

--
-- Name: parking_parkinglot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_parkinglot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_parkinglot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_parkinglotimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_parkinglotimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    parking_lot_id bigint NOT NULL
);


ALTER TABLE public.parking_parkinglotimage OWNER TO postgres;

--
-- Name: parking_parkinglotimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_parkinglotimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_parkinglotimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_parkingprice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_parkingprice (
    id bigint NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    price_per_hour integer NOT NULL,
    parking_lot_id bigint NOT NULL,
    CONSTRAINT parking_parkingprice_price_per_hour_check CHECK ((price_per_hour >= 0))
);


ALTER TABLE public.parking_parkingprice OWNER TO postgres;

--
-- Name: parking_parkingprice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_parkingprice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_parkingprice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_parkingregistrationrequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_parkingregistrationrequest (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    phone character varying(15) NOT NULL,
    email character varying(254) NOT NULL,
    address character varying(255) NOT NULL,
    license_plate character varying(20) NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    note text NOT NULL,
    status character varying(20) NOT NULL,
    reviewed_note character varying(255) NOT NULL,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    parking_lot_id bigint NOT NULL,
    reviewed_by_id integer,
    created_by_id integer
);


ALTER TABLE public.parking_parkingregistrationrequest OWNER TO postgres;

--
-- Name: parking_parkingregistrationrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_parkingregistrationrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_parkingregistrationrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parking_parkinguser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_parkinguser (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    phone character varying(15) NOT NULL,
    email character varying(254) NOT NULL,
    address character varying(255) NOT NULL,
    license_plate character varying(20) NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    parking_lot_id bigint NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    email_verified boolean NOT NULL,
    email_verification_token character varying(64),
    email_verification_sent_at timestamp with time zone
);


ALTER TABLE public.parking_parkinguser OWNER TO postgres;

--
-- Name: parking_parkinguser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_parkinguser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_parkinguser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	parking_user_creator
2	nhan_vien
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Khu vuc	8	add_area
26	Can change Khu vuc	8	change_area
27	Can delete Khu vuc	8	delete_area
28	Can view Khu vuc	8	view_area
29	Can add Bai do xe	9	add_parkinglot
30	Can change Bai do xe	9	change_parkinglot
31	Can delete Bai do xe	9	delete_parkinglot
32	Can view Bai do xe	9	view_parkinglot
33	Can add Nhat ky hoat dong	7	add_activitylog
34	Can change Nhat ky hoat dong	7	change_activitylog
35	Can delete Nhat ky hoat dong	7	delete_activitylog
36	Can view Nhat ky hoat dong	7	view_activitylog
37	Can add Gia gui xe	10	add_parkingprice
38	Can change Gia gui xe	10	change_parkingprice
39	Can delete Gia gui xe	10	delete_parkingprice
40	Can view Gia gui xe	10	view_parkingprice
41	Can add Nguoi su dung do xe	11	add_parkinguser
42	Can change Nguoi su dung do xe	11	change_parkinguser
43	Can delete Nguoi su dung do xe	11	delete_parkinguser
44	Can view Nguoi su dung do xe	11	view_parkinguser
45	Can add Hinh anh bai do xe	12	add_parkinglotimage
46	Can change Hinh anh bai do xe	12	change_parkinglotimage
47	Can delete Hinh anh bai do xe	12	delete_parkinglotimage
48	Can view Hinh anh bai do xe	12	view_parkinglotimage
49	Can add Don dang ky gui xe	13	add_parkingregistrationrequest
50	Can change Don dang ky gui xe	13	change_parkingregistrationrequest
51	Can delete Don dang ky gui xe	13	delete_parkingregistrationrequest
52	Can view Don dang ky gui xe	13	view_parkingregistrationrequest
53	Can add Mã OTP	14	add_otpcode
54	Can change Mã OTP	14	change_otpcode
55	Can delete Mã OTP	14	delete_otpcode
56	Can view Mã OTP	14	view_otpcode
57	Can add introduction page	15	add_introductionpage
58	Can change introduction page	15	change_introductionpage
59	Can delete introduction page	15	delete_introductionpage
60	Can view introduction page	15	view_introductionpage
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$TM2ZjU7UFID9RZrUTlEMBR$pa8kXur2/hRSUDLN8k4JE+8qmRipNYOYqR8g0CWIrBo=	2026-02-01 16:03:51.858+07	t	admin				t	t	2026-02-01 16:00:05.816+07
7	pbkdf2_sha256$1200000$EGFvPkCC2peQFaHmw7UJhh$WH8PGh2WPkKwYiqtTzKDyW7L7T/HuXlrcpu/GeoRvjM=	2026-04-21 14:43:41.523305+07	f	tienpp1	tien		minhtien147896325@gmail.com	f	t	2026-04-21 14:43:35.986788+07
3	pbkdf2_sha256$1200000$gKp94cP1gYJnNXZbFHCPkX$aWllXNWlrZ+H/mjVUPFUHXEJhTJE5Pf0gOIGQm7V1sw=	2026-04-21 14:47:23.03451+07	f	nhanvien				f	t	2026-03-27 08:56:16.866+07
2	pbkdf2_sha256$1200000$5L4UibXAxS7wCvu84dpZ0G$w7Lhmb+OY6F30vdSUATrJY3Aa7XJqFqeYfMRt36cGmg=	2026-05-05 06:54:59.105296+07	t	anhbe				t	t	2026-03-06 11:59:17.042+07
5	pbkdf2_sha256$1200000$pRIpiiZRn5HZCIHdSaRS0F$6R3+4WLBpYHq3JSYbpGhDApwlUf5NCZ4yc2MTJ0i7Lc=	2026-04-20 15:18:50.649276+07	f	thanh123	thanh		cautu669@gmail.com	f	t	2026-04-20 15:16:49.090469+07
6	pbkdf2_sha256$1200000$MSCN6SKcPQ2tMUZldMjP6O$d5CCi7FEm7VtE1HmhlR6vYV3u1ZvxQ+JdFeBaapVNIk=	2026-04-21 07:03:14.88643+07	f	toan123	toan		tquoctoan082@gmail.com	f	t	2026-04-21 07:03:10.995695+07
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	3	1
2	3	2
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	parking	activitylog
8	parking	area
9	parking	parkinglot
10	parking	parkingprice
11	parking	parkinguser
12	parking	parkinglotimage
13	parking	parkingregistrationrequest
14	parking	otpcode
15	parking	introductionpage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-03 10:22:57.750557+07
2	auth	0001_initial	2026-04-03 10:22:57.970568+07
3	admin	0001_initial	2026-04-03 10:22:58.041437+07
4	admin	0002_logentry_remove_auto_add	2026-04-03 10:22:58.06727+07
5	admin	0003_logentry_add_action_flag_choices	2026-04-03 10:22:58.096551+07
6	contenttypes	0002_remove_content_type_name	2026-04-03 10:22:58.159791+07
7	auth	0002_alter_permission_name_max_length	2026-04-03 10:22:58.184128+07
8	auth	0003_alter_user_email_max_length	2026-04-03 10:22:58.209559+07
9	auth	0004_alter_user_username_opts	2026-04-03 10:22:58.232626+07
10	auth	0005_alter_user_last_login_null	2026-04-03 10:22:58.252622+07
11	auth	0006_require_contenttypes_0002	2026-04-03 10:22:58.255635+07
12	auth	0007_alter_validators_add_error_messages	2026-04-03 10:22:58.282785+07
13	auth	0008_alter_user_username_max_length	2026-04-03 10:22:58.322483+07
14	auth	0009_alter_user_last_name_max_length	2026-04-03 10:22:58.342622+07
15	auth	0010_alter_group_name_max_length	2026-04-03 10:22:58.365026+07
16	auth	0011_update_proxy_permissions	2026-04-03 10:22:58.388813+07
17	auth	0012_alter_user_first_name_max_length	2026-04-03 10:22:58.415137+07
18	parking	0001_initial	2026-04-03 10:22:58.602647+07
19	parking	0002_alter_activitylog_options_alter_area_options_and_more	2026-04-03 10:22:58.999446+07
20	parking	0003_remove_parkinglot_parking_type_and_more	2026-04-03 10:22:59.453447+07
21	parking	0004_add_trash_fields	2026-04-03 10:22:59.542333+07
22	parking	0005_parkinguser_email_verification	2026-04-03 10:22:59.628234+07
23	sessions	0001_initial	2026-04-03 10:22:59.659538+07
24	parking	0006_parkinglot_area_sq_m_parkinglot_polygon_geojson	2026-04-05 09:06:09.748336+07
25	parking	0007_parkinglot_long_description_and_more	2026-04-17 09:18:18.464763+07
26	parking	0008_parkinglotimage	2026-04-17 09:18:47.445251+07
27	parking	0009_parkingregistrationrequest	2026-04-17 10:17:45.953521+07
28	parking	0010_parkingregistrationrequest_created_by	2026-04-17 10:55:29.998274+07
29	parking	0011_alter_activitylog_options_alter_area_options_and_more	2026-04-17 11:08:25.112937+07
30	parking	0012_otpcode	2026-04-21 07:00:14.692329+07
31	parking	0013_introductionpage	2026-05-04 14:33:28.098493+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
248jqndbmm0qrw6a35e94di6hov0z3yl	.eJxVjDkOwjAQAP-yNbJ84SMlfd5g7frAAWRLcVIh_o4ipYB2ZjRvCLhvNewjr2FJMIGEyy8jjM_cDpEe2O6dxd62dSF2JOy0g8095dftbP8GFUeFCZTGzAW3gkcrpC7SOXfV5FXhRCKhcJay5yZLz7V0ymBEslqZZDX5WODzBbqNNzc:1w5yT5:iDjfD2tmQ78CBBxpfoi6jYTU9BoiN5BxRxiBJF1-00g	2026-04-10 11:06:43.605+07
5uburnd7mvmxn1dnllrxglybneuk94kb	.eJxVjDkOwjAQAP-yNbJ84SMlfd5g7frAAWRLcVIh_o4ipYB2ZjRvCLhvNewjr2FJMIGEyy8jjM_cDpEe2O6dxd62dSF2JOy0g8095dftbP8GFUeFCZTGzAW3gkcrpC7SOXfV5FXhRCKhcJay5yZLz7V0ymBEslqZZDX5WODzBbqNNzc:1vyQKj:xF_amoKhrH52Q-sHcLpxwDxMYhlThPYRHCKjlbI7FR4	2026-03-20 15:14:53.136+07
bqz01oniw4c9dcb9dyp0vmw1cmjkjmc4	.eJxVjEEOwiAQAP-yZ0MWpBR69N43kGXZStXQpLQn499Nkx70OjOZN0TatxL3JmucMwxwhcsvS8RPqYfID6r3RfFSt3VO6kjUaZsalyyv29n-DQq1AgOYgNk7TcKIHU7eEKFHa_tkBdEFNMI4GUsiQRPn3JuEEpLuLDuRBJ8v0cU4Dw:1w5ySh:oAhtdo_nCyyDk0dCviV3Bm1Ek50rZme1pjoEZhCOOqk	2026-04-10 11:06:19.622+07
yfofl36swgjogqsuuurdwcct148sqv9m	.eJxVjEEOwiAQAP-yZ0MosFB69O4bmt0FpGrapLQn499Nkx70OjOZN4y0b3XcW17HKcEAHVx-GZM883yI9KD5vihZ5m2dWB2JOm1TtyXl1_Vs_waVWoUBnHY-BBNyp9F59kbEMRWOWKzXgbEXKr1PSMWLNbqTFLPFgGgtR23g8wXKEDdB:1vmTN1:4dofHqAu0kjjyxIFjfcMHC-QiDGdGGqg4r7gmQMvrro	2026-02-15 16:03:51.863+07
5e2djngwqs738s5ko15z8mr8gp1lgskp	.eJxVjDkOwjAQAP-yNbJ84SMlfd5g7frAAWRLcVIh_o4ipYB2ZjRvCLhvNewjr2FJMIGEyy8jjM_cDpEe2O6dxd62dSF2JOy0g8095dftbP8GFUeFCZTGzAW3gkcrpC7SOXfV5FXhRCKhcJay5yZLz7V0ymBEslqZZDX5WODzBbqNNzc:1wK37r:Ubfg4Ly-FTukdFYiujQODk7gDwkAWQ7e8q9ahXX0kyc	2026-05-19 06:54:59.107182+07
\.


--
-- Data for Name: parking_activitylog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_activitylog (id, action, created_at, user_id, type) FROM stdin;
1	Xe 36A-362 vao bai BÃI đỗ xe tự phát	2026-03-06 12:10:05.143+07	\N	vehicle
2	Xe 50A-1823 vao bai BÃI đỗ xe mini	2026-03-06 12:39:21.731+07	\N	vehicle
3	Xe 60A-2421 vao bai BÃI GIỮ XE CHÍ THÀNH	2026-03-06 12:39:49.256+07	\N	vehicle
4	Xe 29B-444 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-03-06 12:40:20.59+07	\N	vehicle
5	Xe 92A-9217 vao bai BÃI đỗ xe mini	2026-03-06 12:40:58.396+07	\N	vehicle
6	Xe 50A-22 vao bai BÃI GIỮ XE CHÍ THÀNH	2026-03-27 08:13:46.211+07	\N	vehicle
7	Xe 36A-333 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-03-27 11:05:15.99+07	\N	vehicle
8	Xe 36A-111 vao bai BÃI GIỮ XE CHÍ THÀNH	2026-03-29 20:13:58.756+07	\N	vehicle
9	Xe 29B-432 vao bai BÃI đỗ xe mini	2026-03-29 20:41:59.406+07	\N	vehicle
15	Xe 29B-432 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-05 08:49:53.778838+07	\N	vehicle
19	Xe 29B-4431 vao bai bãi xe mì gói	2026-04-05 08:55:42.003976+07	\N	vehicle
20	Xe 50A-222 vao bai bãi xe mì gói	2026-04-05 08:56:37.459338+07	\N	vehicle
21	Xe 29B-422 vao bai BÃI đỗ xe mini	2026-04-05 10:50:37.694429+07	\N	vehicle
26	Xe 60A-213 vao bai BÃI GIỮ XE CHÍ THÀNH	2026-04-06 08:20:20.310156+07	\N	vehicle
27	Xe 60A-288 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-06 08:32:26.220018+07	\N	vehicle
31	Xe 92A-957 vao bai bãi xe mì gói	2026-04-06 12:35:09.930529+07	\N	vehicle
32	Xe 92A-922 vao bai bãi xe mì gói	2026-04-06 13:52:22.027046+07	\N	vehicle
33	Xe 60A-361 vao bai BÃI GIỮ XE NGUYỄN TRẦN MINH TÂN	2026-04-06 14:35:10.311417+07	\N	vehicle
34	Xe 50A-721 vao bai BÃI GIỮ XE CHÍ THÀNH	2026-04-06 14:39:34.404706+07	\N	vehicle
36	Xe 50A-182 vao bai BÃI đỗ xe mini	2026-04-06 15:01:07.129742+07	\N	vehicle
37	Xe 50A-642 vao bai BÃI GIỮ XE NGUYỄN TRẦN MINH TÂN	2026-04-06 15:01:58.193452+07	\N	vehicle
38	Xe 50A-224 vao bai bãi xe mì gói	2026-04-06 17:10:29.434288+07	\N	vehicle
39	Don dang ky moi sadsad cho bai BÃI GIỮ XE QUỐC TOÀN	2026-04-17 10:18:35.478646+07	\N	system
40	Xe 50A-22 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-17 10:19:07.486747+07	\N	vehicle
42	Xe 29B-422 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-17 10:44:07.481384+07	\N	vehicle
43	Đơn đăng ký mới tien cho bãi BÃI GIỮ XE QUỐC TOÀN	2026-04-18 14:36:48.74877+07	\N	system
44	Xe 92A-321 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-18 14:37:47.619881+07	\N	vehicle
45	Đơn đăng ký mới thanh cho bãi BÃI GIỮ XE QUỐC TOÀN	2026-04-20 15:19:17.259562+07	\N	system
46	Xe 29B-433 vao bai BÃI GIỮ XE QUỐC TOÀN	2026-04-20 15:19:49.182692+07	\N	vehicle
47	Đơn đăng ký mới tien cho bãi BÃI đỗ xe tự phát	2026-04-21 14:43:59.572971+07	\N	system
48	Xe 29B-433 vao bai BÃI đỗ xe tự phát	2026-04-21 14:44:42.266712+07	\N	vehicle
\.


--
-- Data for Name: parking_area; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_area (id, name, description, latitude, longitude, is_deleted, deleted_at) FROM stdin;
1	quận tân bình	Tập trung vào các bãi giữ xe quy mô lớn, an toàn 24/7 phục vụ khách gửi xe dài hạn đi máy bay và nhân viên văn phòng tại các tòa nhà khu vực Cộng Hòa, Trường Chinh. Hệ thống kiểm soát hiện đại giúp bạn yên tâm di chuyển mà không lo về hạ tầng bãi đỗ.	10.8084	106.6468	f	\N
2	quận 10	Đây là khu vực "trung tâm của trung tâm", nơi giao thoa của các trục đường huyết mạch như Ba Tháng Hai, Lê Hồng Phong và Lý Thái Tổ. Đối với một website về bãi giữ xe, tọa độ này nằm rất gần các khu vực trọng điểm như Việt Nam Quốc Tự, Nhà hát Hòa Bình và các bệnh viện lớn, nơi nhu cầu gửi xe luôn ở mức cực kỳ cao.	10.7719	106.6674	f	\N
3	quận 3	Đây là khu vực lõi di sản và trung tâm hành chính, văn hóa của thành phố. Với hệ thống đường phố bàn cờ, nhiều biệt thự cổ và các trục đường rợp bóng cây xanh như Tú Xương, Trương Định hay Bà Huyện Thanh Quan, Quận 3 là khu vực có nhu cầu gửi xe rất cao, đặc biệt là các bãi xe an toàn dành cho ô tô tại các tòa nhà văn phòng và khu vực gần các cơ quan ngoại giao.	10.7818	106.6851	f	\N
\.


--
-- Data for Name: parking_introductionpage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_introductionpage (id, hero_title, hero_description, mission_title, mission_description, about_title, about_description, hero_image, updated_at) FROM stdin;
1	ad	ád	ádsa	ádasd			intro/0-bai-do-xe-o-to.jpg	2026-05-04 15:34:13.239118+07
\.


--
-- Data for Name: parking_otpcode; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_otpcode (id, email, code, created_at, expires_at, is_used) FROM stdin;
1	tquoctoan082@gmail.com	901914	2026-04-21 07:02:46.143797+07	2026-04-21 07:12:46.143504+07	t
2	minhtien147896325@gmail.com	753822	2026-04-21 14:43:07.843899+07	2026-04-21 14:53:07.843229+07	t
\.


--
-- Data for Name: parking_parkinglot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_parkinglot (id, name, address, latitude, longitude, capacity, area_id, district, is_active, price_per_hour, revenue, is_deleted, deleted_at, area_sq_m, polygon_geojson, long_description, short_description) FROM stdin;
4	BÃI GIỮ XE QUỐC TOÀN	339A Đ Nam Kỳ Khởi Nghĩa, Phường, Nhiêu Lộc, Thành phố Hồ Chí Minh, Việt Nam	10.7894	106.6845	35	3	quận 3	t	0	0	f	\N	0		Hầm xe Sky Tower được thiết kế với lối đi rộng rãi, biển báo chỉ dẫn LED thông minh giúp tài xế dễ dàng tìm thấy chỗ trống. Hệ thống phòng cháy chữa cháy (PCCC) đạt tiêu chuẩn quốc tế với các đầu phun tự động và cảm biến khói hiện đại. Bãi xe được phân chia khu vực rõ ràng cho xe máy, ô tô 4 chỗ và xe bán tải. Đội ngũ kỹ thuật trực 24/7 để hỗ trợ kích bình hoặc thay lốp dự phòng cho khách hàng trong trường hợp khẩn cấp.	Bãi đỗ xe cao cấp dành cho cư dân và khách văn phòng với tiêu chuẩn an toàn quốc tế.
3	BÃI GIỮ XE CHÍ THÀNH	370 Cách Mạng Tháng Tám, Phường 9, Quận 3, Thành phố Hồ Chí Minh 70000, Việt Nam	10.7774	106.6825	30	3	quận 3	t	0	0	f	\N	0		Với diện tích mặt bằng lên đến 2.000 m², đây là bãi xe hiếm hoi tại khu vực nội thành hỗ trợ các dòng xe tải nhẹ và xe du lịch cỡ lớn. Bãi xe được trang bị hệ thống chiếu sáng cao áp công suất lớn và tường rào kiên cố bao quanh. Quy trình kiểm soát an ninh nghiêm ngặt, ghi nhận lịch trình ra vào chi tiết cho từng phương tiện. Chúng tôi cung cấp các gói dịch vụ linh hoạt theo giờ, theo ngày hoặc theo tuần với mức giá cạnh tranh nhất khu vực.	Điểm tập kết xe lý tưởng cho việc trung chuyển hàng hóa và gửi xe qua đêm
2	BÃI GIỮ XE NGUYỄN TRẦN MINH TÂN	36 Đ3 Tháng 2, Phường 12, Quận 10, Thành phố Hồ Chí Minh, Việt Nam	10.7761	106.6807	50	2	quận 10	t	0	0	f	\N	0		Trạm dừng chân Digital ứng dụng nền tảng Internet of Things (IoT) để quản lý luồng xe. Mỗi vị trí đỗ đều có cảm biến siêu âm hiển thị đèn xanh/đỏ, giúp người dùng không cần phải chạy lòng vòng tìm chỗ. Website quản lý cho phép chủ xe theo dõi hình ảnh xe của mình trực tiếp qua camera cá nhân hóa. Bãi xe nằm gần các trục đường chính, thuận tiện cho việc di chuyển vào trung tâm thành phố mà không lo về vấn đề kẹt xe tại cửa ngõ.	Bãi xe tích hợp công nghệ quản lý đám mây, hỗ trợ tra cứu tình trạng chỗ trống thời gian thực.
1	BÃI đỗ xe tự phát	40 Cộng Hòa, Khu phố 8, Tân Bình, Thành phố Hồ Chí Minh, Việt Nam	10.8015	106.6508	20	1	quận tân bình	t	0	0	f	\N	0		Nằm trong khu dân cư yên tĩnh, bãi xe Riverside tập trung vào sự an toàn và tin cậy. Toàn bộ khuôn viên được lát gạch chống trơn trượt và có hệ thống thoát nước cực tốt, không bao giờ xảy ra tình trạng ngập úng vào mùa mưa. Chủ xe được cấp mã QR riêng để quản lý thông tin phương tiện và lịch sử thanh toán trên website. Đây là địa điểm ưu tiên cho các hộ gia đình có nhiều xe hoặc những khách hàng đi công tác dài ngày cần một nơi gửi xe an tâm như tại nhà.	Bãi xe an ninh cao, thân thiện, chuyên phục vụ nhu cầu gửi xe lâu dài.
12	BÃI GIỮ XE CHÍ T3213	Hẻm 491 Lê Văn Sỹ, Khu phố 34, Phường Nhiêu Lộc, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 70150, Việt Nam	10.789499969772198	106.67381564137162	25	1	quận tân bình	t	0	0	f	\N	602.88	{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[106.674974,10.788971],[106.675106,10.789221],[106.675259,10.78914],[106.675125,10.788884],[106.674974,10.788971]]]}}	ádsads	Hệ thống đỗ xe tự động hiện đại nhất khu vực trung tâm với công nghệ nhận diện biển số AI.
5	BÃI đỗ xe mini	373 Đ. Lý Thường Kiệt, Phường 9, Tân Bình, Thành phố Hồ Chí Minh, Việt Nam	10.7795	106.6534	35	1	quận tân bình	t	0	0	f	\N	0		Tọa lạc tại vị trí đắc địa nhưng vẫn giữ được không gian xanh mát, bãi xe Công Viên Xanh là lựa chọn lý tưởng cho những ai muốn gửi xe theo tháng. Bãi đỗ có mái che cách nhiệt hiện đại, bảo vệ lớp sơn xe khỏi tác động của thời tiết. Quy trình ra vào đơn giản bằng thẻ từ RFID, giúp tiết kiệm thời gian vào giờ cao điểm. Chúng tôi cung cấp dịch vụ rửa xe và chăm sóc nội thất tại chỗ nếu khách hàng có nhu cầu trong thời gian gửi.	Không gian đỗ xe ngoài trời thoáng đãng, nhiều bóng mát và chi phí hợp lý.
6	bãi xe mì gói	613, Đường Lê Hồng Phong, Khu phố 26, Phường Vườn Lài, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72406, Việt Nam	10.769410724238687	106.67371737123217	30	2	quận 10	t	0	0	f	\N	0		Smart Hub mang đến trải nghiệm đỗ xe không chạm hoàn toàn. Với quy mô 5 tầng hầm, bãi xe sử dụng hệ thống nâng hạ tự động, giúp tối ưu diện tích và đảm bảo an toàn tuyệt đối cho phương tiện. Khách hàng có thể đặt chỗ trước qua ứng dụng và thanh toán tự động qua ví điện tử. Hệ thống camera giám sát 24/7 cùng đội ngũ bảo vệ chuyên nghiệp đảm bảo tài sản của bạn luôn trong tình trạng tốt nhất. Đặc biệt, bãi xe có khu vực sạc nhanh dành riêng cho ô tô điện.	Hệ thống đỗ xe tự động hiện đại nhất khu vực trung tâm với công nghệ nhận diện biển số AI.
\.


--
-- Data for Name: parking_parkinglotimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_parkinglotimage (id, image, created_at, parking_lot_id) FROM stdin;
5	parking_images/download_3.jpg	2026-04-20 12:29:30.24335+07	5
6	parking_images/download_2.jpg	2026-04-20 12:29:30.253202+07	5
7	parking_images/download_5.jpg	2026-04-20 12:29:57.605134+07	4
8	parking_images/download_4.jpg	2026-04-20 12:29:57.61408+07	4
9	parking_images/download_7.jpg	2026-04-20 12:30:27.576769+07	3
10	parking_images/download_6.jpg	2026-04-20 12:30:27.582817+07	3
11	parking_images/images.jpg	2026-04-20 12:31:04.954451+07	2
12	parking_images/download_8.jpg	2026-04-20 12:31:04.964187+07	2
13	parking_images/images_2.jpg	2026-04-20 12:31:27.430547+07	1
14	parking_images/images_1.jpg	2026-04-20 12:31:27.438626+07	1
22	parking_images/Gemini_Generated_Image_nyn7yknyn7yknyn7.png	2026-04-21 11:27:53.423704+07	6
23	parking_images/download_2_aojD1SP.jpg	2026-04-21 14:41:02.485833+07	12
24	parking_images/download_1.jpg	2026-04-21 14:41:02.49977+07	12
\.


--
-- Data for Name: parking_parkingprice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_parkingprice (id, vehicle_type, price_per_hour, parking_lot_id) FROM stdin;
1	car	20000	1
2	motorbike	5000	1
3	bike	3000	1
4	car	15000	2
5	motorbike	4000	2
6	bike	3000	2
7	car	19000	3
8	motorbike	5000	3
9	bike	2000	3
10	car	25000	4
11	motorbike	4000	4
12	bike	2000	4
13	car	18000	5
14	motorbike	3000	5
15	bike	2000	5
\.


--
-- Data for Name: parking_parkingregistrationrequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_parkingregistrationrequest (id, full_name, phone, email, address, license_plate, vehicle_type, note, status, reviewed_note, reviewed_at, created_at, parking_lot_id, reviewed_by_id, created_by_id) FROM stdin;
1	sadsad	0987625172	3231@gmail.com	2 Dương Bá Trạc, Phường Rạch Ông, Quận 8, Thành phố Hồ Chí Minh, Việt Nam	50A-22	motorbike	sdadsa	approved	Da duyet	2026-04-17 10:19:07.488319+07	2026-04-17 10:18:35.475582+07	4	2	\N
3	thanh	0909391233	cautu669@gmail.com	80 Đ. Nguyễn Xí, Phường 26, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	29B-433	motorbike	ádasd	approved	Da duyet	2026-04-20 15:19:49.185684+07	2026-04-20 15:19:17.248141+07	4	2	5
4	tien	090247242	minhtien147896325@gmail.com	80 Đ. Nguyễn Xí, Phường 26, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	29B-433	motorbike	ádsadsad	approved	Da duyet	2026-04-21 14:44:42.268931+07	2026-04-21 14:43:59.558894+07	1	2	7
\.


--
-- Data for Name: parking_parkinguser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parking_parkinguser (id, full_name, phone, email, address, license_plate, vehicle_type, is_active, created_at, parking_lot_id, is_deleted, deleted_at, email_verified, email_verification_token, email_verification_sent_at) FROM stdin;
1	Ben10	0902728222	ben@gmail.com	2 Dương Bá Trạc, Phường Rạch Ông, Quận 8, Thành phố Hồ Chí Minh, Việt Nam	36A-362	car	t	2026-03-06 12:10:05.133+07	1	f	\N	f	\N	\N
2	Meguri	0372927888	1@gmail.com	233A Đ. Phan Văn Trị, Phường 11, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	50A-1823	bike	t	2026-03-06 12:39:21.724+07	5	f	\N	f	\N	\N
3	Hoàng	0937622284	thanh@gmail.com	Trần Văn Ơn,Tân Sơn Nhì,Quận Tân Phú	60A-2421	motorbike	t	2026-03-06 12:39:49.248+07	3	f	\N	f	\N	\N
4	Tân	0973666182	ben@gmail.com	80 Đ. Nguyễn Xí, Phường 26, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	29B-444	motorbike	t	2026-03-06 12:40:20.576+07	4	f	\N	f	\N	\N
5	melody mark	0972682511	meo@gmail.com	233A Đ. Phan Văn Trị, Phường 11, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	92A-9217	car	t	2026-03-06 12:40:58.387+07	5	f	\N	f	\N	\N
40	tien	090247242	minhtien147896325@gmail.com	80 Đ. Nguyễn Xí, Phường 26, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam	29B-433	motorbike	t	2026-04-21 14:44:42.257233+07	1	f	\N	f	BZWC-IUIMRCn7wxLwlhTYPdCKSfcGLghg-3A6qjfVww	2026-04-21 14:44:42.273128+07
34	Hà Minh Tiến	0909361451	minhtien147896325@gmail.com	2 Dương Bá Trạc, Phường Rạch Ông, Quận 8, Thành phố Hồ Chí Minh, Việt Nam	50A-224	car	t	2026-04-06 17:10:29.431074+07	6	f	\N	f	gmzpw6bf96Ya00r14H0g8T0M5ce_qeUc8Ig0SaOP6IY	2026-04-06 17:10:29.437103+07
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 2, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 7, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: parking_activitylog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_activitylog_id_seq', 48, true);


--
-- Name: parking_area_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_area_id_seq', 3, true);


--
-- Name: parking_introductionpage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_introductionpage_id_seq', 1, false);


--
-- Name: parking_otpcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_otpcode_id_seq', 2, true);


--
-- Name: parking_parkinglot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_parkinglot_id_seq', 14, true);


--
-- Name: parking_parkinglotimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_parkinglotimage_id_seq', 24, true);


--
-- Name: parking_parkingprice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_parkingprice_id_seq', 15, true);


--
-- Name: parking_parkingregistrationrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_parkingregistrationrequest_id_seq', 4, true);


--
-- Name: parking_parkinguser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parking_parkinguser_id_seq', 40, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: parking_activitylog parking_activitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_activitylog
    ADD CONSTRAINT parking_activitylog_pkey PRIMARY KEY (id);


--
-- Name: parking_area parking_area_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_area
    ADD CONSTRAINT parking_area_pkey PRIMARY KEY (id);


--
-- Name: parking_introductionpage parking_introductionpage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_introductionpage
    ADD CONSTRAINT parking_introductionpage_pkey PRIMARY KEY (id);


--
-- Name: parking_otpcode parking_otpcode_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_otpcode
    ADD CONSTRAINT parking_otpcode_pkey PRIMARY KEY (id);


--
-- Name: parking_parkinglot parking_parkinglot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinglot
    ADD CONSTRAINT parking_parkinglot_pkey PRIMARY KEY (id);


--
-- Name: parking_parkinglotimage parking_parkinglotimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinglotimage
    ADD CONSTRAINT parking_parkinglotimage_pkey PRIMARY KEY (id);


--
-- Name: parking_parkingprice parking_parkingprice_parking_lot_id_vehicle_type_1e53e004_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingprice
    ADD CONSTRAINT parking_parkingprice_parking_lot_id_vehicle_type_1e53e004_uniq UNIQUE (parking_lot_id, vehicle_type);


--
-- Name: parking_parkingprice parking_parkingprice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingprice
    ADD CONSTRAINT parking_parkingprice_pkey PRIMARY KEY (id);


--
-- Name: parking_parkingregistrationrequest parking_parkingregistrationrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingregistrationrequest
    ADD CONSTRAINT parking_parkingregistrationrequest_pkey PRIMARY KEY (id);


--
-- Name: parking_parkinguser parking_parkinguser_license_plate_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinguser
    ADD CONSTRAINT parking_parkinguser_license_plate_key UNIQUE (license_plate);


--
-- Name: parking_parkinguser parking_parkinguser_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinguser
    ADD CONSTRAINT parking_parkinguser_phone_key UNIQUE (phone);


--
-- Name: parking_parkinguser parking_parkinguser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinguser
    ADD CONSTRAINT parking_parkinguser_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: parking_activitylog_user_id_1ab54554; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_activitylog_user_id_1ab54554 ON public.parking_activitylog USING btree (user_id);


--
-- Name: parking_otp_email_6fe5e9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_otp_email_6fe5e9_idx ON public.parking_otpcode USING btree (email, is_used);


--
-- Name: parking_parkinglot_area_id_58b96768; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkinglot_area_id_58b96768 ON public.parking_parkinglot USING btree (area_id);


--
-- Name: parking_parkinglotimage_parking_lot_id_6a74f534; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkinglotimage_parking_lot_id_6a74f534 ON public.parking_parkinglotimage USING btree (parking_lot_id);


--
-- Name: parking_parkingprice_parking_lot_id_679eb0f8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkingprice_parking_lot_id_679eb0f8 ON public.parking_parkingprice USING btree (parking_lot_id);


--
-- Name: parking_parkingregistrationrequest_created_by_id_c767c86c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkingregistrationrequest_created_by_id_c767c86c ON public.parking_parkingregistrationrequest USING btree (created_by_id);


--
-- Name: parking_parkingregistrationrequest_parking_lot_id_92e53492; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkingregistrationrequest_parking_lot_id_92e53492 ON public.parking_parkingregistrationrequest USING btree (parking_lot_id);


--
-- Name: parking_parkingregistrationrequest_reviewed_by_id_3c083892; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkingregistrationrequest_reviewed_by_id_3c083892 ON public.parking_parkingregistrationrequest USING btree (reviewed_by_id);


--
-- Name: parking_parkinguser_license_plate_b2aaedd4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkinguser_license_plate_b2aaedd4_like ON public.parking_parkinguser USING btree (license_plate varchar_pattern_ops);


--
-- Name: parking_parkinguser_parking_lot_id_2e21f68b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkinguser_parking_lot_id_2e21f68b ON public.parking_parkinguser USING btree (parking_lot_id);


--
-- Name: parking_parkinguser_phone_d3d6da6e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX parking_parkinguser_phone_d3d6da6e_like ON public.parking_parkinguser USING btree (phone varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_activitylog parking_activitylog_user_id_1ab54554_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_activitylog
    ADD CONSTRAINT parking_activitylog_user_id_1ab54554_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkinglot parking_parkinglot_area_id_58b96768_fk_parking_area_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinglot
    ADD CONSTRAINT parking_parkinglot_area_id_58b96768_fk_parking_area_id FOREIGN KEY (area_id) REFERENCES public.parking_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkinglotimage parking_parkinglotim_parking_lot_id_6a74f534_fk_parking_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinglotimage
    ADD CONSTRAINT parking_parkinglotim_parking_lot_id_6a74f534_fk_parking_p FOREIGN KEY (parking_lot_id) REFERENCES public.parking_parkinglot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkingprice parking_parkingprice_parking_lot_id_679eb0f8_fk_parking_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingprice
    ADD CONSTRAINT parking_parkingprice_parking_lot_id_679eb0f8_fk_parking_p FOREIGN KEY (parking_lot_id) REFERENCES public.parking_parkinglot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkingregistrationrequest parking_parkingregis_created_by_id_c767c86c_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingregistrationrequest
    ADD CONSTRAINT parking_parkingregis_created_by_id_c767c86c_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkingregistrationrequest parking_parkingregis_parking_lot_id_92e53492_fk_parking_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingregistrationrequest
    ADD CONSTRAINT parking_parkingregis_parking_lot_id_92e53492_fk_parking_p FOREIGN KEY (parking_lot_id) REFERENCES public.parking_parkinglot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkingregistrationrequest parking_parkingregis_reviewed_by_id_3c083892_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkingregistrationrequest
    ADD CONSTRAINT parking_parkingregis_reviewed_by_id_3c083892_fk_auth_user FOREIGN KEY (reviewed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parking_parkinguser parking_parkinguser_parking_lot_id_2e21f68b_fk_parking_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_parkinguser
    ADD CONSTRAINT parking_parkinguser_parking_lot_id_2e21f68b_fk_parking_p FOREIGN KEY (parking_lot_id) REFERENCES public.parking_parkinglot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict KHL9nQvZDMz5d5Am3tC83OKT76oxglC2BM9MG00kVA2PM5dRWvKEksME5Jtj5sU

