"""
Django settings for webgis_parking project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, seePP
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


def _load_local_env():
    env_file = BASE_DIR / ".env"
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wjzinukcg5wkl*g)3r(xv(8*0d7f=(dkn=zdyd-tv+-ri!nu_d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

MANAGER_URL_PREFIX = "manager/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'parking', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webgis_parking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'parking.context_processors.auth_navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'webgis_parking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'webgis_parking'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("MAILTRAP_HOST", "live.smtp.mailtrap.io")
EMAIL_PORT = int(os.getenv("MAILTRAP_PORT", "587"))
EMAIL_HOST_USER = os.getenv("MAILTRAP_USER", "api")
EMAIL_HOST_PASSWORD = os.getenv("MAILTRAP_PASSWORD", "")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv("MAILTRAP_FROM_EMAIL", "no-reply@demomailtrap.co")
MAILTRAP_TO_EMAIL = os.getenv("MAILTRAP_TO_EMAIL", "minhtien147896325@gmail.com,1250080194@sv.hcmunre.edu.vn")
MAILTRAP_SANDBOX_HOST = os.getenv("MAILTRAP_SANDBOX_HOST", "sandbox.smtp.mailtrap.io")
MAILTRAP_SANDBOX_PORT = int(os.getenv("MAILTRAP_SANDBOX_PORT", "587"))
MAILTRAP_SANDBOX_USER = os.getenv("MAILTRAP_SANDBOX_USER", "")
MAILTRAP_SANDBOX_PASSWORD = os.getenv("MAILTRAP_SANDBOX_PASSWORD", "")
MAILTRAP_SANDBOX_FROM_EMAIL = os.getenv("MAILTRAP_SANDBOX_FROM_EMAIL", "no-reply@mailtrap.local")
MAILTRAP_SANDBOX_TO_EMAIL = os.getenv("MAILTRAP_SANDBOX_TO_EMAIL", "")
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL", "")
SENDGRID_FROM_NAME = os.getenv("SENDGRID_FROM_NAME", "Parking GIS")
SENDGRID_VALIDATION_API_KEY = os.getenv("SENDGRID_VALIDATION_API_KEY", "")
SENDGRID_REQUIRE_VALIDATION = os.getenv("SENDGRID_REQUIRE_VALIDATION", "true").lower() in ("1", "true", "yes")



